3 gene tests
PawelDabrowski83/genAlgo pull request #12
Opened 2020-12-18 08:43 UTC by Surfboy678

added tests:
- Array Size Gene With Mock
- Value Under The Index Gene With Mock

2020-12-18 10:20 UTC, PawelDabrowski83 requested changes
There are some issuses to be resolved.

2020-12-18 10:20 UTC, PawelDabrowski83 commented on pom.xml
> +        <java.version>11</java.version>
why do we change java version? if it is needed, should we change also in maven.compiler?

2020-12-18 10:20 UTC, PawelDabrowski83 commented on src/main/java/RandomProvider.java
> +    int getRandom();
int getRandom(int rangeTo);
int getRandom(int rangeFrom, int rangeTo);

We want to set a range for random numbers from 0 to bound (exclusive).

2020-12-18 10:20 UTC, PawelDabrowski83 commented on src/main/java/main.java
> +public class main {
Main.class - it is convention to start class names with big letters

2020-12-18 10:20 UTC, PawelDabrowski83 commented on src/test/java/RandomProviderTest.java
> +    int boundedRandomValue = ThreadLocalRandom.current().nextInt(0, 5);
this is part of implementation, not needed here

2020-12-18 10:20 UTC, PawelDabrowski83 commented on src/test/java/RandomProviderTest.java
> +public class RandomProviderTest {
This is RandomProviderTest. This class should not test Genes.

2020-12-18 15:42 UTC, PawelDabrowski83 requested changes

2020-12-18 15:42 UTC, PawelDabrowski83 commented on src/test/java/GeneTest.java
> +  public void testValueUnderTheIndexGeneWithMock() {
I am missing the point of this test. We should check if every char in Gene.values is equal to expectedNumber. Why not to check it with for each loop? It should work for all elements in char.

2020-12-19 07:42 UTC, Surfboy678 commented on pom.xml
> +            <version>4.12</version>
without this I can't import :
org.junit.Assert;
 org.junit.Test;
org.junit.runner.RunWith;

2020-12-19 07:55 UTC, PawelDabrowski83 commented on pom.xml
> +            <version>4.12</version>
ok, let it stay and we will refactor later :)

2020-12-19 08:43 UTC, PawelDabrowski83 approved these changes
There are some things to be changed but I think it will work

2020-12-19 19:50 UTC, KamilKamilS approved these changes

2020-12-19 20:37 UTC, merged