Dev s2 v2
PawelDabrowski83/genAlgo pull request #40
Opened 2020-12-30 20:58 UTC by Surfboy678

In both cases only tests are passed setFitnessFullMatch.
Any ideas?

2020-12-30 21:04 UTC, PawelDabrowski83 commented
Please check issues #39 and #41 because they are crucial for understanding/fixing and passing the tests.

2020-12-30 21:08 UTC, PawelDabrowski83 requested changes

2020-12-30 21:08 UTC, PawelDabrowski83 commented on src/main/java/com/facebook/genAlgo/evaluator/Variant1EvaluatorImpl.java
> +    float delta = gene.getValues()[0] - target;
this is not stated directly in docs, but we assume that delta is never below zero, so Math.abs() will solve this

2020-12-30 21:08 UTC, PawelDabrowski83 commented on src/main/java/com/facebook/genAlgo/evaluator/Variant1EvaluatorImpl.java
> +    return (float) (1 / (1 + log(1 + delta)));
tests use other logarithm function, hence they will not pass

2020-12-30 21:08 UTC, PawelDabrowski83 commented on src/main/java/com/facebook/genAlgo/evaluator/Variant2EvaluatorImpl.java
> +        float delta = gene.getValues()[0] - target;
Math.abs() as in Variant1 comment

2020-12-30 21:08 UTC, PawelDabrowski83 commented on src/main/java/com/facebook/genAlgo/evaluator/Variant2EvaluatorImpl.java
> +        return(float) ((655- delta) / 65535);
value 655 is wrong, probably a typo

2020-12-31 12:04 UTC, Surfboy678 commented
In the second variant, it passes only setFitnessFullMatch.

2020-12-31 12:34 UTC, PawelDabrowski83 approved these changes
Now it passes all tests, but you should first update your local dev-s3 branch with latest bugfix and then merge it into your PR.

2020-12-31 14:39 UTC, PawelDabrowski83 approved these changes

2020-12-31 15:22 UTC, merged