53 crossover tests
PawelDabrowski83/genAlgo pull request #60
Opened 2021-01-09 00:33 UTC by KamilKamilS

Crossover tests created for four strategies of CrossoverService.

2021-01-09 11:20 UTC, PawelDabrowski83 requested changes

2021-01-09 11:20 UTC, PawelDabrowski83 commented on src/test/java/com/facebook/genAlgo/crossover/OddBitesCrossoverServiceImplTest.java
> +    @MethodSource("evenBitesCrossoverProvider")
odd bites

2021-01-09 11:20 UTC, PawelDabrowski83 commented on src/test/java/com/facebook/genAlgo/crossover/BitPairCrossoverServiceImplTest.java
> +    private Stream<Arguments> bitPairCrossoverProvider() {
this method should be static, otherwise it throws org.junit.platform.commons.PreconditionViolationException

2021-01-09 11:23 UTC, PawelDabrowski83 commented
I think it might be better for our TDD to push changes that can be compiled (so: with empty classes and method implementations), because sometimes there are compile errors in tests, which are hard to notice. So we should not go to implementation level, when tests are not compiling. Of course test should be failing, because they describe acceptance conditions.

2021-01-09 15:24 UTC, KamilKamilS commented on src/test/java/com/facebook/genAlgo/crossover/BitPairCrossoverServiceImplTest.java
> +                Arguments.of(33, 5000, (char) 169, (char) 4864),
Yes, it is correct first bit is on position 1, not 0. I think it was not precisely described in docs.

2021-01-09 15:31 UTC, KamilKamilS commented on src/test/java/com/facebook/genAlgo/crossover/BitPairCrossoverServiceImplTest.java
> +        when(randomProviderGene1.getRandom(anyInt())).thenReturn(gene1Val);
Yes we can use gene.setValue(). I was also wondering about it. So I will change it, it will be a simpler solution than using mock

2021-01-09 18:35 UTC, KamilKamilS commented
Plese review. I have changed test classes and added empty classes with empty method.

2021-01-09 20:50 UTC, PawelDabrowski83 reviewed
It is almost ready. Still methods used as an argument providers for parameterized tests should be declared static. They throw exceptions now.

2021-01-09 22:07 UTC, KamilKamilS commented
Right, sorry I forget about this

2021-01-10 07:56 UTC, PawelDabrowski83 approved these changes

2021-01-10 08:30 UTC, merged